//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CmsEntities : DbContext
    {
        public CmsEntities()
            : base("name=CmsEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tb_basicuser>()
                .HasMany(u => u.Roles)
                .WithMany(r => r.Users)
                .Map(m =>
                {
                    m.MapLeftKey("userid");
                    m.MapRightKey("roleid");
                    m.ToTable("tb_userrole");
                });
        }

        public virtual DbSet<tb_basiccontent> tb_basiccontent { get; set; }
        public virtual DbSet<tb_contenttype> tb_contenttype { get; set; }
        public virtual DbSet<tb_authority> tb_authority { get; set; }
        public virtual DbSet<tb_basicuser> tb_basicuser { get; set; }
        public virtual DbSet<tb_dictionary> tb_dictionary { get; set; }
        public virtual DbSet<tb_dictype> tb_dictype { get; set; }
        public virtual DbSet<tb_role> tb_role { get; set; }
        public virtual DbSet<tb_roleauthority> tb_roleauthority { get; set; }
        public virtual DbSet<tb_sysparams> tb_sysparams { get; set; }
        public virtual DbSet<tb_userrole> tb_userrole { get; set; }
    }
}
