//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsEntity
{
    using System;
    using System.Collections.Generic;

    public partial class TB_BasicUser : BaseEntity
    {
        public TB_BasicUser() : base()
        {

        }

        public int ID { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public string PasswordSalt { get; set; }
        public string UserName { get; set; }
        public string UserStatus { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string UserType { get; set; }
    }
}
