//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// tb_basicuser
    /// </summary>
    public partial class tb_basicuser : BaseEntity
    {
        public virtual ICollection<tb_role> Roles { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UserAccount { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string UserPassword { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string PasswordSalt { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string UserName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> UserStatus { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> UserType { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> IsDeleted { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> CreateUser { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> UpdateUser { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
