//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BasicContent
    {
        public int ID { get; set; }
        public Nullable<int> ContentType { get; set; }
        public string Source { get; set; }
        public string ContentTitle { get; set; }
        public string ContentSubTitle { get; set; }
        public string CoverPictureUrl { get; set; }
        public Nullable<System.DateTime> ValidStartTime { get; set; }
        public Nullable<System.DateTime> ValidEndTime { get; set; }
        public Nullable<int> OrderNO { get; set; }
        public Nullable<int> PageViewQua { get; set; }
        public Nullable<int> ForwardQua { get; set; }
        public Nullable<int> PointQua { get; set; }
        public Nullable<int> CommentQua { get; set; }
        public string AttachmentUrl { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
