//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_news
    {
        public long ID { get; set; }
        public Nullable<int> NewsType { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContent { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int UpdateUser { get; set; }
    }
}
